### ISSUE TITLE
What is Theme Check?

### ISSUE THREAD

**Issue by ghost** [anhskohbo/wp-cli-themecheck#3]
Based on the name it seems this CLI package is intended to run https://wordpress.org/plugins/theme-check/. Am I correct in that assumption?

**Comment by anhskohbo** [comment]
Yes, this package just wrapped [theme-check](https://wordpress.org/plugins/theme-check/) plugin. It can't run without that plugin.

My idea is when write this CLI is I need a quick way to run theme-check :)

**Comment by ghost** [comment]
@anhskohbo super cool. thanks for sharing this valuable tool. while I was geeking out at some of the cli stuff earlier I also ran across the [vip scanner plugin](https://wordpress.org/plugins/vip-scanner/), which wraps a vip scanner lib. not sure what it'd take to adapt this tool to it but could be neat to see given you've got the skillz to make it happen.
