### ISSUE TITLE
Use a non-zero exit status when tests do not pass

### ISSUE THREAD

**Issue by frankiejarrett** [anhskohbo/wp-cli-themecheck#4]
In order to use this package in automated workflows, the command should only use a `0` exit status when a theme passes all the tests:

```
Success: Congratulations! Theme is passed the tests!
$ echo $?
0
```

As it stands today, the exit status is always`0`, even for errors. So in order to integrate the command into a CI/CD pipeline you have to grep the output and pray it never changes:

```
Error: One or more errors were found for Primer!
$ echo $?
0
```

**Comment by anhskohbo** [comment]
Closed https://github.com/anhskohbo/wp-cli-themecheck/pull/5
